name: CI/CD Pipeline including Discord Integration

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Running coding style
        run: |
          docker run --rm --security-opt "label:disable" -i -v "$(pwd)":"/mnt/delivery" -v "$(pwd)":"/mnt/reports" ghcr.io/epitech/coding-style-checker:latest "/mnt/delivery" "/mnt/reports"

      - name: Run the action
        uses: docker://foxoundone/github_cicd
        env:
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          PUSH_AUTHOR: ${{ github.actor }}
          PUSH_MESSAGE: ${{ github.event.head_commit.message }}
          PUSH_URL: ${{ github.event.head_commit.url }}
          DOC_REPOSITORY: ${{ secrets.DOCUMENTATION_REPO }}
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

      - name: Ignore CiCd on mirrored repository
        run: |
          echo ".github/" >> .gitignore

      - name: Mirror project to school repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.TARGET_REPOSITORY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}